[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"
  
[build.environment]
  HUGO_VERSION = "0.91.2-1798BD3F"

[context.deploy-preview]
  command = "yarn build:preview"
